{% set name = "mne-kit-gui" %}
{% set version = "1.3.0" %}
{% set build = 1 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mne_kit_gui-{{ version }}.tar.gz
  sha256: a270acc2dfd3e2127e7d58bbf8bad1c5675d6168b8845dff78748ab0aa12d263

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - mne-base >=0.23
    - mayavi
    - nibabel

test:
  imports:
    - mne_kit_gui
    - mne_kit_gui.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mne-tools/mne-kit-gui
  summary: A module for KIT MEG coregistration.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
