{% set name = "mne-kit-gui" %}
{% set version = "1.2.0" %}
{% set build = 2 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mne-kit-gui-{{ version }}.tar.gz
  sha256: 0fb99ac061e76f3983ab39dc74a0eac2459ceffc4a6b8fb37bea0922f6353d2e

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - mne-base >=0.23
    - mayavi
    - nibabel

test:
  imports:
    - mne_kit_gui
    - mne_kit_gui.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-kit-gui
  summary: A module for KIT MEG coregistration.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
