{% set name = "mne-kit-gui" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mne-kit-gui-{{ version }}.tar.gz
  sha256: ca319b34355a515c2d599f3149d71a4e8ba30309b7e3cf044f9ebb6a13b3ee18

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - mne-base >=0.23
    - mayavi
    - pyqt >=5.12
    - nibabel

test:
  imports:
    - mne_kit_gui
    - mne_kit_gui.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mne-tools/mne-kit-gui
  summary: A module for KIT MEG coregistration.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
